Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BOK.Data;
using BOK.Models;
using Microsoft.Extensions.Logging;

namespace BOK.Controllers
{
    public class OffersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<OffersController> _logger;

        public OffersController(ApplicationDbContext context,
            ILogger<OffersController> logger)
        {
            _logger = logger;
            _context = context;
        }

        // GET: Offers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Offer.ToListAsync());
        }

        // GET: Offers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // GET: Offers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Speed,OpticalFibre,MonthlyCost,CommitmentPeriod")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                _logger.LogInformation(offer.Name + " - offer has been created");
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
            return View(offer);
        }

        // POST: Offers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Speed,OpticalFibre,MonthlyCost,CommitmentPeriod")] Offer offer)
        {
            if (id != offer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offer);
                    _logger.LogInformation(offer.Name + " - offer has been modified");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(offer);
        }

        // GET: Offers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var offer = await _context.Offer.FindAsync(id);
            _context.Offer.Remove(offer);
            await _context.SaveChangesAsync();
            _logger.LogInformation(offer.Name + " - offer has been deleted");
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(int id)
        {
            return _context.Offer.Any(e => e.Id == id);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BOK.Data;
using BOK.Models;
using Microsoft.Extensions.Logging;

namespace BOK.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<OrdersController> _logger;

        public OrdersController(ApplicationDbContext context,
            ILogger<OrdersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.Offer);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Offer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["OfferId"] = new SelectList(_context.Offer, "Id", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,OfferId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                _logger.LogInformation(order.Id + " - order has been created for:" + order.FirstName + order.LastName);
                return RedirectToAction(nameof(Index));
            }
            ViewData["OfferId"] = new SelectList(_context.Offer, "Id", "Description", order.OfferId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["OfferId"] = new SelectList(_context.Offer, "Id", "Name", order.OfferId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,OfferId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    _logger.LogInformation(order.Id + " - order has been modified for:" + order.FirstName + order.LastName);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OfferId"] = new SelectList(_context.Offer, "Id", "Description", order.OfferId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Offer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Order.FindAsync(id);
            _context.Order.Remove(order);
            _logger.LogInformation(order.Id + " - order has been deleted for:" + order.FirstName + order.LastName);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    var user = UserManager.GetUserAsync(User).Result;
}

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BOK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/custom.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body id="body-pd">
<script src="~/js/site.js"></script>
<script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<div class="nav_mobile">
    <a href="javascript:void(0);" class="nav_mobile-icon" onclick="navMobile()">
        <i class="fa fa-bars"></i>
    </a>
    <div id="nav_mobile-links">
        <span class="nav_mobile_logo-name nav_logo">BOK</span>

        <a asp-controller="Users" asp-action="List" class="nav_link">
            <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users</span>
        </a>
        
        <a asp-controller="Offers" asp-action="Index" class="nav_link">
            <i class='bx bx-bar-chart-alt-2 nav_icon'></i> <span class="nav_name">Offers</span>
        </a>

        <a class="nav_link" asp-controller="Orders" asp-action="Index">
            <i class='bx bx-money-withdraw nav_icon'></i> <span class="nav_name">Orders</span>
        </a>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false" onclick="sidebar()">
                <img src="/img/user-icon.jpg" class="rounded-circle me-2">
                @if (User.Identity.IsAuthenticated)
                {
                    <span class="nav_name">@user.FirstName @user.LastName</span>
                }
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li>
                    <form class="form-inline" asp-controller="Account" asp-action="Logout" method="post">
                        <button type="submit" class="dropdown-item">Logout</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>
<header class="header" id="header">
    <a href="javascript:void(0);" class="nav_mobile-icon" onclick="navMobile()">
        <i class="fa fa-bars"></i>
    </a>

</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <span class="nav_logo-name">BOK</span>
            <div class="nav_list">

                <a asp-controller="Users" asp-action="List" class="nav_link">
                    <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users</span>
                </a>

                <a class="nav_link" asp-controller="Offers" asp-action="Index"> 
                    <i class='bx bx-bar-chart-alt-2 nav_icon'></i> <span class="nav_name">Offers</span>
                </a>

                <a class="nav_link" asp-controller="Orders" asp-action="Index">
                    <i class='bx bx-money-withdraw nav_icon'></i> <span class="nav_name">Orders</span>
                </a>
            </div>
        </div>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false" onclick="sidebar()">
                <img src="/img/user-icon.jpg" class="rounded-circle me-2">
                @if (User.Identity.IsAuthenticated)
                {
                    <span class="nav_name">@user.FirstName @user.LastName</span>
                }
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li>

                    <button id="myBtn" class="dropdown-item">Profile</button>

                </li>
                <li>
                    <form class="form-inline" asp-controller="Account" asp-action="Logout" method="post">
                        <button type="submit" class="dropdown-item">Logout</button>
                    </form>
                </li>
            </ul>
        </div>
    </nav>
</div>
<div id="myModal" class="modal">


    <div class="modal-content">
        <span class="close">&times;</span>
        <p>
            <img src="/img/user-icon.jpg" class="rounded-circle me-2">
        </p>


        <form id="account" method="post">


            <div class="form-group row">
                <input type="text" value="@user.FirstName" disabled="disabled">
                <label>Name</label>
            </div>


            <div class="form-group row">
                <input type="text" value="@user.LastName" disabled="disabled">
                <label>Last Name</label>
            </div>

            <div class="form-group row">
                <input type="email" value="a@admin.com" disabled="disabled"/>
                <label>e-mail address</label>
            </div>


        </form>

    </div>
</div>
<script>    
            var modal = document.getElementById("myModal");
            var btn = document.getElementById("myBtn");
            var span = document.getElementsByClassName("close")[0];
            btn.onclick = function () {
                modal.style.display = "block";
            }
            span.onclick = function () {
                modal.style.display = "none";
            }
            window.onclick = function (event) {
                if (event.target == modal) {
                    modal.style.display = "none";
                }
            }
        </script>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@await RenderSectionAsync("Scripts", required: false)
</body>

</html>